var foods = [
    {
        Num:1,
        Name:'A米汉堡',
        Price:16,
        MonthlySold:8148,
        StartCost:10,
        Time:45,
        Img:'img/1cde.jpg'
    },{
        Num:2,
        Name:'杨记小厨',
        Price:17.5,
        MonthlySold:4639,
        StartCost:10,
        Time:38,
        Img:'img/3a31d.jpg'
    },{
        Num:3,
        Name:'杨铭宇黄焖鸡米饭',
        Price:18,
        MonthlySold:2571,
        StartCost:10,
        Time:25,
        Img:'img/9ecd.jpg'
    },{
        Num:4,
        Name:'烤肉拌饭',
        Price:18,
        MonthlySold:2347,
        StartCost:0,
        Time:29,
        Img:'img/d64c553.jpg'
    },{
        Num:5,
        Name:'有名堂（焗饭、小炒）',
        Price:14,
        MonthlySold:2156,
        StartCost:0,
        Time:43,
        Img:'img/3d875.jpg'
    },{
        Num:6,
        Name:'翔仔湾（美食特惠！）',
        Price:20,
        MonthlySold:1803,
        StartCost:10,
        Time:34,
        Img:'img/880259b.jpg'
    },{
        Num:7,
        Name:'食尚便当',
        Price:21,
        MonthlySold:3554,
        StartCost:12,
        Time:45,
        Img:'img/1b718f.jpg'
    },{
        Num:8,
        Name:'格子那只水饺',
        Price:13,
        MonthlySold:2682,
        StartCost:10,
        Time:23,
        Img:'img/4c981e4.jpg'
    }
]